/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.oasis.xAL.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.oasis.xAL.util.XALAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class XALItemProviderAdapterFactory extends XALAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public XALItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AddressDetails} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressDetailsItemProvider addressDetailsItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AddressDetails}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressDetailsAdapter() {
		if (addressDetailsItemProvider == null) {
			addressDetailsItemProvider = new AddressDetailsItemProvider(this);
		}

		return addressDetailsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AddressIdentifierType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressIdentifierTypeItemProvider addressIdentifierTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AddressIdentifierType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressIdentifierTypeAdapter() {
		if (addressIdentifierTypeItemProvider == null) {
			addressIdentifierTypeItemProvider = new AddressIdentifierTypeItemProvider(this);
		}

		return addressIdentifierTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AddressLatitudeDirectionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressLatitudeDirectionTypeItemProvider addressLatitudeDirectionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AddressLatitudeDirectionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressLatitudeDirectionTypeAdapter() {
		if (addressLatitudeDirectionTypeItemProvider == null) {
			addressLatitudeDirectionTypeItemProvider = new AddressLatitudeDirectionTypeItemProvider(this);
		}

		return addressLatitudeDirectionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AddressLatitudeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressLatitudeTypeItemProvider addressLatitudeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AddressLatitudeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressLatitudeTypeAdapter() {
		if (addressLatitudeTypeItemProvider == null) {
			addressLatitudeTypeItemProvider = new AddressLatitudeTypeItemProvider(this);
		}

		return addressLatitudeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AddressLinesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressLinesTypeItemProvider addressLinesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AddressLinesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressLinesTypeAdapter() {
		if (addressLinesTypeItemProvider == null) {
			addressLinesTypeItemProvider = new AddressLinesTypeItemProvider(this);
		}

		return addressLinesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AddressLineType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressLineTypeItemProvider addressLineTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AddressLineType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressLineTypeAdapter() {
		if (addressLineTypeItemProvider == null) {
			addressLineTypeItemProvider = new AddressLineTypeItemProvider(this);
		}

		return addressLineTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AddressLongitudeDirectionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressLongitudeDirectionTypeItemProvider addressLongitudeDirectionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AddressLongitudeDirectionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressLongitudeDirectionTypeAdapter() {
		if (addressLongitudeDirectionTypeItemProvider == null) {
			addressLongitudeDirectionTypeItemProvider = new AddressLongitudeDirectionTypeItemProvider(this);
		}

		return addressLongitudeDirectionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AddressLongitudeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressLongitudeTypeItemProvider addressLongitudeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AddressLongitudeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressLongitudeTypeAdapter() {
		if (addressLongitudeTypeItemProvider == null) {
			addressLongitudeTypeItemProvider = new AddressLongitudeTypeItemProvider(this);
		}

		return addressLongitudeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AddressType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressTypeItemProvider addressTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AddressType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressTypeAdapter() {
		if (addressTypeItemProvider == null) {
			addressTypeItemProvider = new AddressTypeItemProvider(this);
		}

		return addressTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AdministrativeAreaNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AdministrativeAreaNameTypeItemProvider administrativeAreaNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AdministrativeAreaNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAdministrativeAreaNameTypeAdapter() {
		if (administrativeAreaNameTypeItemProvider == null) {
			administrativeAreaNameTypeItemProvider = new AdministrativeAreaNameTypeItemProvider(this);
		}

		return administrativeAreaNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.AdministrativeAreaType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AdministrativeAreaTypeItemProvider administrativeAreaTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.AdministrativeAreaType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAdministrativeAreaTypeAdapter() {
		if (administrativeAreaTypeItemProvider == null) {
			administrativeAreaTypeItemProvider = new AdministrativeAreaTypeItemProvider(this);
		}

		return administrativeAreaTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.BarcodeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BarcodeTypeItemProvider barcodeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.BarcodeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBarcodeTypeAdapter() {
		if (barcodeTypeItemProvider == null) {
			barcodeTypeItemProvider = new BarcodeTypeItemProvider(this);
		}

		return barcodeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.BuildingNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BuildingNameTypeItemProvider buildingNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.BuildingNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBuildingNameTypeAdapter() {
		if (buildingNameTypeItemProvider == null) {
			buildingNameTypeItemProvider = new BuildingNameTypeItemProvider(this);
		}

		return buildingNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.CountryNameCodeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CountryNameCodeTypeItemProvider countryNameCodeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.CountryNameCodeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCountryNameCodeTypeAdapter() {
		if (countryNameCodeTypeItemProvider == null) {
			countryNameCodeTypeItemProvider = new CountryNameCodeTypeItemProvider(this);
		}

		return countryNameCodeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.CountryNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CountryNameTypeItemProvider countryNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.CountryNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCountryNameTypeAdapter() {
		if (countryNameTypeItemProvider == null) {
			countryNameTypeItemProvider = new CountryNameTypeItemProvider(this);
		}

		return countryNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.CountryType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CountryTypeItemProvider countryTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.CountryType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCountryTypeAdapter() {
		if (countryTypeItemProvider == null) {
			countryTypeItemProvider = new CountryTypeItemProvider(this);
		}

		return countryTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.DepartmentNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DepartmentNameTypeItemProvider departmentNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.DepartmentNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDepartmentNameTypeAdapter() {
		if (departmentNameTypeItemProvider == null) {
			departmentNameTypeItemProvider = new DepartmentNameTypeItemProvider(this);
		}

		return departmentNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.DepartmentType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DepartmentTypeItemProvider departmentTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.DepartmentType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDepartmentTypeAdapter() {
		if (departmentTypeItemProvider == null) {
			departmentTypeItemProvider = new DepartmentTypeItemProvider(this);
		}

		return departmentTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.DependentLocalityNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependentLocalityNameTypeItemProvider dependentLocalityNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.DependentLocalityNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDependentLocalityNameTypeAdapter() {
		if (dependentLocalityNameTypeItemProvider == null) {
			dependentLocalityNameTypeItemProvider = new DependentLocalityNameTypeItemProvider(this);
		}

		return dependentLocalityNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.DependentLocalityNumberType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependentLocalityNumberTypeItemProvider dependentLocalityNumberTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.DependentLocalityNumberType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDependentLocalityNumberTypeAdapter() {
		if (dependentLocalityNumberTypeItemProvider == null) {
			dependentLocalityNumberTypeItemProvider = new DependentLocalityNumberTypeItemProvider(this);
		}

		return dependentLocalityNumberTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.DependentLocalityType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependentLocalityTypeItemProvider dependentLocalityTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.DependentLocalityType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDependentLocalityTypeAdapter() {
		if (dependentLocalityTypeItemProvider == null) {
			dependentLocalityTypeItemProvider = new DependentLocalityTypeItemProvider(this);
		}

		return dependentLocalityTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.DependentThoroughfareType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependentThoroughfareTypeItemProvider dependentThoroughfareTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.DependentThoroughfareType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDependentThoroughfareTypeAdapter() {
		if (dependentThoroughfareTypeItemProvider == null) {
			dependentThoroughfareTypeItemProvider = new DependentThoroughfareTypeItemProvider(this);
		}

		return dependentThoroughfareTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.EndorsementLineCodeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EndorsementLineCodeTypeItemProvider endorsementLineCodeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.EndorsementLineCodeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEndorsementLineCodeTypeAdapter() {
		if (endorsementLineCodeTypeItemProvider == null) {
			endorsementLineCodeTypeItemProvider = new EndorsementLineCodeTypeItemProvider(this);
		}

		return endorsementLineCodeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.FirmNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FirmNameTypeItemProvider firmNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.FirmNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFirmNameTypeAdapter() {
		if (firmNameTypeItemProvider == null) {
			firmNameTypeItemProvider = new FirmNameTypeItemProvider(this);
		}

		return firmNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.FirmType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FirmTypeItemProvider firmTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.FirmType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFirmTypeAdapter() {
		if (firmTypeItemProvider == null) {
			firmTypeItemProvider = new FirmTypeItemProvider(this);
		}

		return firmTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.KeyLineCodeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KeyLineCodeTypeItemProvider keyLineCodeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.KeyLineCodeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKeyLineCodeTypeAdapter() {
		if (keyLineCodeTypeItemProvider == null) {
			keyLineCodeTypeItemProvider = new KeyLineCodeTypeItemProvider(this);
		}

		return keyLineCodeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.LargeMailUserIdentifierType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LargeMailUserIdentifierTypeItemProvider largeMailUserIdentifierTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.LargeMailUserIdentifierType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLargeMailUserIdentifierTypeAdapter() {
		if (largeMailUserIdentifierTypeItemProvider == null) {
			largeMailUserIdentifierTypeItemProvider = new LargeMailUserIdentifierTypeItemProvider(this);
		}

		return largeMailUserIdentifierTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.LargeMailUserNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LargeMailUserNameTypeItemProvider largeMailUserNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.LargeMailUserNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLargeMailUserNameTypeAdapter() {
		if (largeMailUserNameTypeItemProvider == null) {
			largeMailUserNameTypeItemProvider = new LargeMailUserNameTypeItemProvider(this);
		}

		return largeMailUserNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.LargeMailUserType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LargeMailUserTypeItemProvider largeMailUserTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.LargeMailUserType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLargeMailUserTypeAdapter() {
		if (largeMailUserTypeItemProvider == null) {
			largeMailUserTypeItemProvider = new LargeMailUserTypeItemProvider(this);
		}

		return largeMailUserTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.LocalityNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalityNameTypeItemProvider localityNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.LocalityNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalityNameTypeAdapter() {
		if (localityNameTypeItemProvider == null) {
			localityNameTypeItemProvider = new LocalityNameTypeItemProvider(this);
		}

		return localityNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.LocalityType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalityTypeItemProvider localityTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.LocalityType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalityTypeAdapter() {
		if (localityTypeItemProvider == null) {
			localityTypeItemProvider = new LocalityTypeItemProvider(this);
		}

		return localityTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.MailStopNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MailStopNameTypeItemProvider mailStopNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.MailStopNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMailStopNameTypeAdapter() {
		if (mailStopNameTypeItemProvider == null) {
			mailStopNameTypeItemProvider = new MailStopNameTypeItemProvider(this);
		}

		return mailStopNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.MailStopNumberType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MailStopNumberTypeItemProvider mailStopNumberTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.MailStopNumberType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMailStopNumberTypeAdapter() {
		if (mailStopNumberTypeItemProvider == null) {
			mailStopNumberTypeItemProvider = new MailStopNumberTypeItemProvider(this);
		}

		return mailStopNumberTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.MailStopType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MailStopTypeItemProvider mailStopTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.MailStopType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMailStopTypeAdapter() {
		if (mailStopTypeItemProvider == null) {
			mailStopTypeItemProvider = new MailStopTypeItemProvider(this);
		}

		return mailStopTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostalCodeNumberExtensionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostalCodeNumberExtensionTypeItemProvider postalCodeNumberExtensionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostalCodeNumberExtensionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostalCodeNumberExtensionTypeAdapter() {
		if (postalCodeNumberExtensionTypeItemProvider == null) {
			postalCodeNumberExtensionTypeItemProvider = new PostalCodeNumberExtensionTypeItemProvider(this);
		}

		return postalCodeNumberExtensionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostalCodeNumberType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostalCodeNumberTypeItemProvider postalCodeNumberTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostalCodeNumberType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostalCodeNumberTypeAdapter() {
		if (postalCodeNumberTypeItemProvider == null) {
			postalCodeNumberTypeItemProvider = new PostalCodeNumberTypeItemProvider(this);
		}

		return postalCodeNumberTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostalCodeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostalCodeTypeItemProvider postalCodeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostalCodeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostalCodeTypeAdapter() {
		if (postalCodeTypeItemProvider == null) {
			postalCodeTypeItemProvider = new PostalCodeTypeItemProvider(this);
		}

		return postalCodeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostalRouteNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostalRouteNameTypeItemProvider postalRouteNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostalRouteNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostalRouteNameTypeAdapter() {
		if (postalRouteNameTypeItemProvider == null) {
			postalRouteNameTypeItemProvider = new PostalRouteNameTypeItemProvider(this);
		}

		return postalRouteNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostalRouteNumberType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostalRouteNumberTypeItemProvider postalRouteNumberTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostalRouteNumberType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostalRouteNumberTypeAdapter() {
		if (postalRouteNumberTypeItemProvider == null) {
			postalRouteNumberTypeItemProvider = new PostalRouteNumberTypeItemProvider(this);
		}

		return postalRouteNumberTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostalRouteType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostalRouteTypeItemProvider postalRouteTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostalRouteType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostalRouteTypeAdapter() {
		if (postalRouteTypeItemProvider == null) {
			postalRouteTypeItemProvider = new PostalRouteTypeItemProvider(this);
		}

		return postalRouteTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostalServiceElementsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostalServiceElementsTypeItemProvider postalServiceElementsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostalServiceElementsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostalServiceElementsTypeAdapter() {
		if (postalServiceElementsTypeItemProvider == null) {
			postalServiceElementsTypeItemProvider = new PostalServiceElementsTypeItemProvider(this);
		}

		return postalServiceElementsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostBoxNumberExtensionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostBoxNumberExtensionTypeItemProvider postBoxNumberExtensionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostBoxNumberExtensionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostBoxNumberExtensionTypeAdapter() {
		if (postBoxNumberExtensionTypeItemProvider == null) {
			postBoxNumberExtensionTypeItemProvider = new PostBoxNumberExtensionTypeItemProvider(this);
		}

		return postBoxNumberExtensionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostBoxNumberPrefixType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostBoxNumberPrefixTypeItemProvider postBoxNumberPrefixTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostBoxNumberPrefixType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostBoxNumberPrefixTypeAdapter() {
		if (postBoxNumberPrefixTypeItemProvider == null) {
			postBoxNumberPrefixTypeItemProvider = new PostBoxNumberPrefixTypeItemProvider(this);
		}

		return postBoxNumberPrefixTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostBoxNumberSuffixType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostBoxNumberSuffixTypeItemProvider postBoxNumberSuffixTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostBoxNumberSuffixType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostBoxNumberSuffixTypeAdapter() {
		if (postBoxNumberSuffixTypeItemProvider == null) {
			postBoxNumberSuffixTypeItemProvider = new PostBoxNumberSuffixTypeItemProvider(this);
		}

		return postBoxNumberSuffixTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostBoxNumberType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostBoxNumberTypeItemProvider postBoxNumberTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostBoxNumberType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostBoxNumberTypeAdapter() {
		if (postBoxNumberTypeItemProvider == null) {
			postBoxNumberTypeItemProvider = new PostBoxNumberTypeItemProvider(this);
		}

		return postBoxNumberTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostBoxType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostBoxTypeItemProvider postBoxTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostBoxType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostBoxTypeAdapter() {
		if (postBoxTypeItemProvider == null) {
			postBoxTypeItemProvider = new PostBoxTypeItemProvider(this);
		}

		return postBoxTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostOfficeNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostOfficeNameTypeItemProvider postOfficeNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostOfficeNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostOfficeNameTypeAdapter() {
		if (postOfficeNameTypeItemProvider == null) {
			postOfficeNameTypeItemProvider = new PostOfficeNameTypeItemProvider(this);
		}

		return postOfficeNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostOfficeNumberType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostOfficeNumberTypeItemProvider postOfficeNumberTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostOfficeNumberType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostOfficeNumberTypeAdapter() {
		if (postOfficeNumberTypeItemProvider == null) {
			postOfficeNumberTypeItemProvider = new PostOfficeNumberTypeItemProvider(this);
		}

		return postOfficeNumberTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostOfficeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostOfficeTypeItemProvider postOfficeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostOfficeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostOfficeTypeAdapter() {
		if (postOfficeTypeItemProvider == null) {
			postOfficeTypeItemProvider = new PostOfficeTypeItemProvider(this);
		}

		return postOfficeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostTownNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostTownNameTypeItemProvider postTownNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostTownNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostTownNameTypeAdapter() {
		if (postTownNameTypeItemProvider == null) {
			postTownNameTypeItemProvider = new PostTownNameTypeItemProvider(this);
		}

		return postTownNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostTownSuffixType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostTownSuffixTypeItemProvider postTownSuffixTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostTownSuffixType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostTownSuffixTypeAdapter() {
		if (postTownSuffixTypeItemProvider == null) {
			postTownSuffixTypeItemProvider = new PostTownSuffixTypeItemProvider(this);
		}

		return postTownSuffixTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PostTownType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostTownTypeItemProvider postTownTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PostTownType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostTownTypeAdapter() {
		if (postTownTypeItemProvider == null) {
			postTownTypeItemProvider = new PostTownTypeItemProvider(this);
		}

		return postTownTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PremiseLocationType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PremiseLocationTypeItemProvider premiseLocationTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PremiseLocationType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPremiseLocationTypeAdapter() {
		if (premiseLocationTypeItemProvider == null) {
			premiseLocationTypeItemProvider = new PremiseLocationTypeItemProvider(this);
		}

		return premiseLocationTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PremiseNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PremiseNameTypeItemProvider premiseNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PremiseNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPremiseNameTypeAdapter() {
		if (premiseNameTypeItemProvider == null) {
			premiseNameTypeItemProvider = new PremiseNameTypeItemProvider(this);
		}

		return premiseNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PremiseNumberPrefixType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PremiseNumberPrefixTypeItemProvider premiseNumberPrefixTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PremiseNumberPrefixType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPremiseNumberPrefixTypeAdapter() {
		if (premiseNumberPrefixTypeItemProvider == null) {
			premiseNumberPrefixTypeItemProvider = new PremiseNumberPrefixTypeItemProvider(this);
		}

		return premiseNumberPrefixTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PremiseNumberRangeFromType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PremiseNumberRangeFromTypeItemProvider premiseNumberRangeFromTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PremiseNumberRangeFromType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPremiseNumberRangeFromTypeAdapter() {
		if (premiseNumberRangeFromTypeItemProvider == null) {
			premiseNumberRangeFromTypeItemProvider = new PremiseNumberRangeFromTypeItemProvider(this);
		}

		return premiseNumberRangeFromTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PremiseNumberRangeToType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PremiseNumberRangeToTypeItemProvider premiseNumberRangeToTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PremiseNumberRangeToType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPremiseNumberRangeToTypeAdapter() {
		if (premiseNumberRangeToTypeItemProvider == null) {
			premiseNumberRangeToTypeItemProvider = new PremiseNumberRangeToTypeItemProvider(this);
		}

		return premiseNumberRangeToTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PremiseNumberRangeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PremiseNumberRangeTypeItemProvider premiseNumberRangeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PremiseNumberRangeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPremiseNumberRangeTypeAdapter() {
		if (premiseNumberRangeTypeItemProvider == null) {
			premiseNumberRangeTypeItemProvider = new PremiseNumberRangeTypeItemProvider(this);
		}

		return premiseNumberRangeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PremiseNumberSuffixType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PremiseNumberSuffixTypeItemProvider premiseNumberSuffixTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PremiseNumberSuffixType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPremiseNumberSuffixTypeAdapter() {
		if (premiseNumberSuffixTypeItemProvider == null) {
			premiseNumberSuffixTypeItemProvider = new PremiseNumberSuffixTypeItemProvider(this);
		}

		return premiseNumberSuffixTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PremiseNumberType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PremiseNumberTypeItemProvider premiseNumberTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PremiseNumberType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPremiseNumberTypeAdapter() {
		if (premiseNumberTypeItemProvider == null) {
			premiseNumberTypeItemProvider = new PremiseNumberTypeItemProvider(this);
		}

		return premiseNumberTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.PremiseType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PremiseTypeItemProvider premiseTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.PremiseType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPremiseTypeAdapter() {
		if (premiseTypeItemProvider == null) {
			premiseTypeItemProvider = new PremiseTypeItemProvider(this);
		}

		return premiseTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.SortingCodeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SortingCodeTypeItemProvider sortingCodeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.SortingCodeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSortingCodeTypeAdapter() {
		if (sortingCodeTypeItemProvider == null) {
			sortingCodeTypeItemProvider = new SortingCodeTypeItemProvider(this);
		}

		return sortingCodeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.SubAdministrativeAreaNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubAdministrativeAreaNameTypeItemProvider subAdministrativeAreaNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.SubAdministrativeAreaNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubAdministrativeAreaNameTypeAdapter() {
		if (subAdministrativeAreaNameTypeItemProvider == null) {
			subAdministrativeAreaNameTypeItemProvider = new SubAdministrativeAreaNameTypeItemProvider(this);
		}

		return subAdministrativeAreaNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.SubAdministrativeAreaType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubAdministrativeAreaTypeItemProvider subAdministrativeAreaTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.SubAdministrativeAreaType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubAdministrativeAreaTypeAdapter() {
		if (subAdministrativeAreaTypeItemProvider == null) {
			subAdministrativeAreaTypeItemProvider = new SubAdministrativeAreaTypeItemProvider(this);
		}

		return subAdministrativeAreaTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.SubPremiseLocationType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubPremiseLocationTypeItemProvider subPremiseLocationTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.SubPremiseLocationType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubPremiseLocationTypeAdapter() {
		if (subPremiseLocationTypeItemProvider == null) {
			subPremiseLocationTypeItemProvider = new SubPremiseLocationTypeItemProvider(this);
		}

		return subPremiseLocationTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.SubPremiseNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubPremiseNameTypeItemProvider subPremiseNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.SubPremiseNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubPremiseNameTypeAdapter() {
		if (subPremiseNameTypeItemProvider == null) {
			subPremiseNameTypeItemProvider = new SubPremiseNameTypeItemProvider(this);
		}

		return subPremiseNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.SubPremiseNumberPrefixType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubPremiseNumberPrefixTypeItemProvider subPremiseNumberPrefixTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.SubPremiseNumberPrefixType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubPremiseNumberPrefixTypeAdapter() {
		if (subPremiseNumberPrefixTypeItemProvider == null) {
			subPremiseNumberPrefixTypeItemProvider = new SubPremiseNumberPrefixTypeItemProvider(this);
		}

		return subPremiseNumberPrefixTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.SubPremiseNumberSuffixType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubPremiseNumberSuffixTypeItemProvider subPremiseNumberSuffixTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.SubPremiseNumberSuffixType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubPremiseNumberSuffixTypeAdapter() {
		if (subPremiseNumberSuffixTypeItemProvider == null) {
			subPremiseNumberSuffixTypeItemProvider = new SubPremiseNumberSuffixTypeItemProvider(this);
		}

		return subPremiseNumberSuffixTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.SubPremiseNumberType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubPremiseNumberTypeItemProvider subPremiseNumberTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.SubPremiseNumberType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubPremiseNumberTypeAdapter() {
		if (subPremiseNumberTypeItemProvider == null) {
			subPremiseNumberTypeItemProvider = new SubPremiseNumberTypeItemProvider(this);
		}

		return subPremiseNumberTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.SubPremiseType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubPremiseTypeItemProvider subPremiseTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.SubPremiseType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubPremiseTypeAdapter() {
		if (subPremiseTypeItemProvider == null) {
			subPremiseTypeItemProvider = new SubPremiseTypeItemProvider(this);
		}

		return subPremiseTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.SupplementaryPostalServiceDataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SupplementaryPostalServiceDataTypeItemProvider supplementaryPostalServiceDataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.SupplementaryPostalServiceDataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSupplementaryPostalServiceDataTypeAdapter() {
		if (supplementaryPostalServiceDataTypeItemProvider == null) {
			supplementaryPostalServiceDataTypeItemProvider = new SupplementaryPostalServiceDataTypeItemProvider(this);
		}

		return supplementaryPostalServiceDataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfareLeadingTypeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfareLeadingTypeTypeItemProvider thoroughfareLeadingTypeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfareLeadingTypeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfareLeadingTypeTypeAdapter() {
		if (thoroughfareLeadingTypeTypeItemProvider == null) {
			thoroughfareLeadingTypeTypeItemProvider = new ThoroughfareLeadingTypeTypeItemProvider(this);
		}

		return thoroughfareLeadingTypeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfareNameType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfareNameTypeItemProvider thoroughfareNameTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfareNameType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfareNameTypeAdapter() {
		if (thoroughfareNameTypeItemProvider == null) {
			thoroughfareNameTypeItemProvider = new ThoroughfareNameTypeItemProvider(this);
		}

		return thoroughfareNameTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfareNumberFromType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfareNumberFromTypeItemProvider thoroughfareNumberFromTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfareNumberFromType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfareNumberFromTypeAdapter() {
		if (thoroughfareNumberFromTypeItemProvider == null) {
			thoroughfareNumberFromTypeItemProvider = new ThoroughfareNumberFromTypeItemProvider(this);
		}

		return thoroughfareNumberFromTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfareNumberPrefixType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfareNumberPrefixTypeItemProvider thoroughfareNumberPrefixTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfareNumberPrefixType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfareNumberPrefixTypeAdapter() {
		if (thoroughfareNumberPrefixTypeItemProvider == null) {
			thoroughfareNumberPrefixTypeItemProvider = new ThoroughfareNumberPrefixTypeItemProvider(this);
		}

		return thoroughfareNumberPrefixTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfareNumberRangeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfareNumberRangeTypeItemProvider thoroughfareNumberRangeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfareNumberRangeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfareNumberRangeTypeAdapter() {
		if (thoroughfareNumberRangeTypeItemProvider == null) {
			thoroughfareNumberRangeTypeItemProvider = new ThoroughfareNumberRangeTypeItemProvider(this);
		}

		return thoroughfareNumberRangeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfareNumberSuffixType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfareNumberSuffixTypeItemProvider thoroughfareNumberSuffixTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfareNumberSuffixType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfareNumberSuffixTypeAdapter() {
		if (thoroughfareNumberSuffixTypeItemProvider == null) {
			thoroughfareNumberSuffixTypeItemProvider = new ThoroughfareNumberSuffixTypeItemProvider(this);
		}

		return thoroughfareNumberSuffixTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfareNumberToType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfareNumberToTypeItemProvider thoroughfareNumberToTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfareNumberToType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfareNumberToTypeAdapter() {
		if (thoroughfareNumberToTypeItemProvider == null) {
			thoroughfareNumberToTypeItemProvider = new ThoroughfareNumberToTypeItemProvider(this);
		}

		return thoroughfareNumberToTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfareNumberType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfareNumberTypeItemProvider thoroughfareNumberTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfareNumberType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfareNumberTypeAdapter() {
		if (thoroughfareNumberTypeItemProvider == null) {
			thoroughfareNumberTypeItemProvider = new ThoroughfareNumberTypeItemProvider(this);
		}

		return thoroughfareNumberTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfarePostDirectionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfarePostDirectionTypeItemProvider thoroughfarePostDirectionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfarePostDirectionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfarePostDirectionTypeAdapter() {
		if (thoroughfarePostDirectionTypeItemProvider == null) {
			thoroughfarePostDirectionTypeItemProvider = new ThoroughfarePostDirectionTypeItemProvider(this);
		}

		return thoroughfarePostDirectionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfarePreDirectionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfarePreDirectionTypeItemProvider thoroughfarePreDirectionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfarePreDirectionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfarePreDirectionTypeAdapter() {
		if (thoroughfarePreDirectionTypeItemProvider == null) {
			thoroughfarePreDirectionTypeItemProvider = new ThoroughfarePreDirectionTypeItemProvider(this);
		}

		return thoroughfarePreDirectionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfareTrailingTypeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfareTrailingTypeTypeItemProvider thoroughfareTrailingTypeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfareTrailingTypeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfareTrailingTypeTypeAdapter() {
		if (thoroughfareTrailingTypeTypeItemProvider == null) {
			thoroughfareTrailingTypeTypeItemProvider = new ThoroughfareTrailingTypeTypeItemProvider(this);
		}

		return thoroughfareTrailingTypeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.ThoroughfareType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThoroughfareTypeItemProvider thoroughfareTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.ThoroughfareType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThoroughfareTypeAdapter() {
		if (thoroughfareTypeItemProvider == null) {
			thoroughfareTypeItemProvider = new ThoroughfareTypeItemProvider(this);
		}

		return thoroughfareTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.DocumentRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentRootItemProvider documentRootItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.DocumentRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentRootAdapter() {
		if (documentRootItemProvider == null) {
			documentRootItemProvider = new DocumentRootItemProvider(this);
		}

		return documentRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.oasis.xAL.XALType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XALTypeItemProvider xalTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.oasis.xAL.XALType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXALTypeAdapter() {
		if (xalTypeItemProvider == null) {
			xalTypeItemProvider = new XALTypeItemProvider(this);
		}

		return xalTypeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (addressDetailsItemProvider != null) addressDetailsItemProvider.dispose();
		if (addressIdentifierTypeItemProvider != null) addressIdentifierTypeItemProvider.dispose();
		if (addressLatitudeDirectionTypeItemProvider != null) addressLatitudeDirectionTypeItemProvider.dispose();
		if (addressLatitudeTypeItemProvider != null) addressLatitudeTypeItemProvider.dispose();
		if (addressLinesTypeItemProvider != null) addressLinesTypeItemProvider.dispose();
		if (addressLineTypeItemProvider != null) addressLineTypeItemProvider.dispose();
		if (addressLongitudeDirectionTypeItemProvider != null) addressLongitudeDirectionTypeItemProvider.dispose();
		if (addressLongitudeTypeItemProvider != null) addressLongitudeTypeItemProvider.dispose();
		if (addressTypeItemProvider != null) addressTypeItemProvider.dispose();
		if (administrativeAreaNameTypeItemProvider != null) administrativeAreaNameTypeItemProvider.dispose();
		if (administrativeAreaTypeItemProvider != null) administrativeAreaTypeItemProvider.dispose();
		if (barcodeTypeItemProvider != null) barcodeTypeItemProvider.dispose();
		if (buildingNameTypeItemProvider != null) buildingNameTypeItemProvider.dispose();
		if (countryNameCodeTypeItemProvider != null) countryNameCodeTypeItemProvider.dispose();
		if (countryNameTypeItemProvider != null) countryNameTypeItemProvider.dispose();
		if (countryTypeItemProvider != null) countryTypeItemProvider.dispose();
		if (departmentNameTypeItemProvider != null) departmentNameTypeItemProvider.dispose();
		if (departmentTypeItemProvider != null) departmentTypeItemProvider.dispose();
		if (dependentLocalityNameTypeItemProvider != null) dependentLocalityNameTypeItemProvider.dispose();
		if (dependentLocalityNumberTypeItemProvider != null) dependentLocalityNumberTypeItemProvider.dispose();
		if (dependentLocalityTypeItemProvider != null) dependentLocalityTypeItemProvider.dispose();
		if (dependentThoroughfareTypeItemProvider != null) dependentThoroughfareTypeItemProvider.dispose();
		if (endorsementLineCodeTypeItemProvider != null) endorsementLineCodeTypeItemProvider.dispose();
		if (firmNameTypeItemProvider != null) firmNameTypeItemProvider.dispose();
		if (firmTypeItemProvider != null) firmTypeItemProvider.dispose();
		if (keyLineCodeTypeItemProvider != null) keyLineCodeTypeItemProvider.dispose();
		if (largeMailUserIdentifierTypeItemProvider != null) largeMailUserIdentifierTypeItemProvider.dispose();
		if (largeMailUserNameTypeItemProvider != null) largeMailUserNameTypeItemProvider.dispose();
		if (largeMailUserTypeItemProvider != null) largeMailUserTypeItemProvider.dispose();
		if (localityNameTypeItemProvider != null) localityNameTypeItemProvider.dispose();
		if (localityTypeItemProvider != null) localityTypeItemProvider.dispose();
		if (mailStopNameTypeItemProvider != null) mailStopNameTypeItemProvider.dispose();
		if (mailStopNumberTypeItemProvider != null) mailStopNumberTypeItemProvider.dispose();
		if (mailStopTypeItemProvider != null) mailStopTypeItemProvider.dispose();
		if (postalCodeNumberExtensionTypeItemProvider != null) postalCodeNumberExtensionTypeItemProvider.dispose();
		if (postalCodeNumberTypeItemProvider != null) postalCodeNumberTypeItemProvider.dispose();
		if (postalCodeTypeItemProvider != null) postalCodeTypeItemProvider.dispose();
		if (postalRouteNameTypeItemProvider != null) postalRouteNameTypeItemProvider.dispose();
		if (postalRouteNumberTypeItemProvider != null) postalRouteNumberTypeItemProvider.dispose();
		if (postalRouteTypeItemProvider != null) postalRouteTypeItemProvider.dispose();
		if (postalServiceElementsTypeItemProvider != null) postalServiceElementsTypeItemProvider.dispose();
		if (postBoxNumberExtensionTypeItemProvider != null) postBoxNumberExtensionTypeItemProvider.dispose();
		if (postBoxNumberPrefixTypeItemProvider != null) postBoxNumberPrefixTypeItemProvider.dispose();
		if (postBoxNumberSuffixTypeItemProvider != null) postBoxNumberSuffixTypeItemProvider.dispose();
		if (postBoxNumberTypeItemProvider != null) postBoxNumberTypeItemProvider.dispose();
		if (postBoxTypeItemProvider != null) postBoxTypeItemProvider.dispose();
		if (postOfficeNameTypeItemProvider != null) postOfficeNameTypeItemProvider.dispose();
		if (postOfficeNumberTypeItemProvider != null) postOfficeNumberTypeItemProvider.dispose();
		if (postOfficeTypeItemProvider != null) postOfficeTypeItemProvider.dispose();
		if (postTownNameTypeItemProvider != null) postTownNameTypeItemProvider.dispose();
		if (postTownSuffixTypeItemProvider != null) postTownSuffixTypeItemProvider.dispose();
		if (postTownTypeItemProvider != null) postTownTypeItemProvider.dispose();
		if (premiseLocationTypeItemProvider != null) premiseLocationTypeItemProvider.dispose();
		if (premiseNameTypeItemProvider != null) premiseNameTypeItemProvider.dispose();
		if (premiseNumberPrefixTypeItemProvider != null) premiseNumberPrefixTypeItemProvider.dispose();
		if (premiseNumberRangeFromTypeItemProvider != null) premiseNumberRangeFromTypeItemProvider.dispose();
		if (premiseNumberRangeToTypeItemProvider != null) premiseNumberRangeToTypeItemProvider.dispose();
		if (premiseNumberRangeTypeItemProvider != null) premiseNumberRangeTypeItemProvider.dispose();
		if (premiseNumberSuffixTypeItemProvider != null) premiseNumberSuffixTypeItemProvider.dispose();
		if (premiseNumberTypeItemProvider != null) premiseNumberTypeItemProvider.dispose();
		if (premiseTypeItemProvider != null) premiseTypeItemProvider.dispose();
		if (sortingCodeTypeItemProvider != null) sortingCodeTypeItemProvider.dispose();
		if (subAdministrativeAreaNameTypeItemProvider != null) subAdministrativeAreaNameTypeItemProvider.dispose();
		if (subAdministrativeAreaTypeItemProvider != null) subAdministrativeAreaTypeItemProvider.dispose();
		if (subPremiseLocationTypeItemProvider != null) subPremiseLocationTypeItemProvider.dispose();
		if (subPremiseNameTypeItemProvider != null) subPremiseNameTypeItemProvider.dispose();
		if (subPremiseNumberPrefixTypeItemProvider != null) subPremiseNumberPrefixTypeItemProvider.dispose();
		if (subPremiseNumberSuffixTypeItemProvider != null) subPremiseNumberSuffixTypeItemProvider.dispose();
		if (subPremiseNumberTypeItemProvider != null) subPremiseNumberTypeItemProvider.dispose();
		if (subPremiseTypeItemProvider != null) subPremiseTypeItemProvider.dispose();
		if (supplementaryPostalServiceDataTypeItemProvider != null) supplementaryPostalServiceDataTypeItemProvider.dispose();
		if (thoroughfareLeadingTypeTypeItemProvider != null) thoroughfareLeadingTypeTypeItemProvider.dispose();
		if (thoroughfareNameTypeItemProvider != null) thoroughfareNameTypeItemProvider.dispose();
		if (thoroughfareNumberFromTypeItemProvider != null) thoroughfareNumberFromTypeItemProvider.dispose();
		if (thoroughfareNumberPrefixTypeItemProvider != null) thoroughfareNumberPrefixTypeItemProvider.dispose();
		if (thoroughfareNumberRangeTypeItemProvider != null) thoroughfareNumberRangeTypeItemProvider.dispose();
		if (thoroughfareNumberSuffixTypeItemProvider != null) thoroughfareNumberSuffixTypeItemProvider.dispose();
		if (thoroughfareNumberToTypeItemProvider != null) thoroughfareNumberToTypeItemProvider.dispose();
		if (thoroughfareNumberTypeItemProvider != null) thoroughfareNumberTypeItemProvider.dispose();
		if (thoroughfarePostDirectionTypeItemProvider != null) thoroughfarePostDirectionTypeItemProvider.dispose();
		if (thoroughfarePreDirectionTypeItemProvider != null) thoroughfarePreDirectionTypeItemProvider.dispose();
		if (thoroughfareTrailingTypeTypeItemProvider != null) thoroughfareTrailingTypeTypeItemProvider.dispose();
		if (thoroughfareTypeItemProvider != null) thoroughfareTypeItemProvider.dispose();
		if (documentRootItemProvider != null) documentRootItemProvider.dispose();
		if (xalTypeItemProvider != null) xalTypeItemProvider.dispose();
	}

}
