/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.citygml.transportation.provider;

import java.util.ArrayList;
import java.util.Collection;

import net.opengis.citygml.transportation.util.TransportationAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class TransportationItemProviderAdapterFactory extends TransportationAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TransportationItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.opengis.citygml.transportation.AuxiliaryTrafficAreaPropertyType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AuxiliaryTrafficAreaPropertyTypeItemProvider auxiliaryTrafficAreaPropertyTypeItemProvider;

	/**
	 * This creates an adapter for a {@link net.opengis.citygml.transportation.AuxiliaryTrafficAreaPropertyType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAuxiliaryTrafficAreaPropertyTypeAdapter() {
		if (auxiliaryTrafficAreaPropertyTypeItemProvider == null) {
			auxiliaryTrafficAreaPropertyTypeItemProvider = new AuxiliaryTrafficAreaPropertyTypeItemProvider(this);
		}

		return auxiliaryTrafficAreaPropertyTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.opengis.citygml.transportation.AuxiliaryTrafficAreaType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AuxiliaryTrafficAreaTypeItemProvider auxiliaryTrafficAreaTypeItemProvider;

	/**
	 * This creates an adapter for a {@link net.opengis.citygml.transportation.AuxiliaryTrafficAreaType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAuxiliaryTrafficAreaTypeAdapter() {
		if (auxiliaryTrafficAreaTypeItemProvider == null) {
			auxiliaryTrafficAreaTypeItemProvider = new AuxiliaryTrafficAreaTypeItemProvider(this);
		}

		return auxiliaryTrafficAreaTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.opengis.citygml.transportation.DocumentRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentRootItemProvider documentRootItemProvider;

	/**
	 * This creates an adapter for a {@link net.opengis.citygml.transportation.DocumentRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentRootAdapter() {
		if (documentRootItemProvider == null) {
			documentRootItemProvider = new DocumentRootItemProvider(this);
		}

		return documentRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.opengis.citygml.transportation.RailwayType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RailwayTypeItemProvider railwayTypeItemProvider;

	/**
	 * This creates an adapter for a {@link net.opengis.citygml.transportation.RailwayType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRailwayTypeAdapter() {
		if (railwayTypeItemProvider == null) {
			railwayTypeItemProvider = new RailwayTypeItemProvider(this);
		}

		return railwayTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.opengis.citygml.transportation.RoadType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoadTypeItemProvider roadTypeItemProvider;

	/**
	 * This creates an adapter for a {@link net.opengis.citygml.transportation.RoadType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoadTypeAdapter() {
		if (roadTypeItemProvider == null) {
			roadTypeItemProvider = new RoadTypeItemProvider(this);
		}

		return roadTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.opengis.citygml.transportation.SquareType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SquareTypeItemProvider squareTypeItemProvider;

	/**
	 * This creates an adapter for a {@link net.opengis.citygml.transportation.SquareType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSquareTypeAdapter() {
		if (squareTypeItemProvider == null) {
			squareTypeItemProvider = new SquareTypeItemProvider(this);
		}

		return squareTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.opengis.citygml.transportation.TrackType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrackTypeItemProvider trackTypeItemProvider;

	/**
	 * This creates an adapter for a {@link net.opengis.citygml.transportation.TrackType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrackTypeAdapter() {
		if (trackTypeItemProvider == null) {
			trackTypeItemProvider = new TrackTypeItemProvider(this);
		}

		return trackTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.opengis.citygml.transportation.TrafficAreaPropertyType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrafficAreaPropertyTypeItemProvider trafficAreaPropertyTypeItemProvider;

	/**
	 * This creates an adapter for a {@link net.opengis.citygml.transportation.TrafficAreaPropertyType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrafficAreaPropertyTypeAdapter() {
		if (trafficAreaPropertyTypeItemProvider == null) {
			trafficAreaPropertyTypeItemProvider = new TrafficAreaPropertyTypeItemProvider(this);
		}

		return trafficAreaPropertyTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.opengis.citygml.transportation.TrafficAreaType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrafficAreaTypeItemProvider trafficAreaTypeItemProvider;

	/**
	 * This creates an adapter for a {@link net.opengis.citygml.transportation.TrafficAreaType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrafficAreaTypeAdapter() {
		if (trafficAreaTypeItemProvider == null) {
			trafficAreaTypeItemProvider = new TrafficAreaTypeItemProvider(this);
		}

		return trafficAreaTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.opengis.citygml.transportation.TransportationComplexType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransportationComplexTypeItemProvider transportationComplexTypeItemProvider;

	/**
	 * This creates an adapter for a {@link net.opengis.citygml.transportation.TransportationComplexType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransportationComplexTypeAdapter() {
		if (transportationComplexTypeItemProvider == null) {
			transportationComplexTypeItemProvider = new TransportationComplexTypeItemProvider(this);
		}

		return transportationComplexTypeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (auxiliaryTrafficAreaPropertyTypeItemProvider != null) auxiliaryTrafficAreaPropertyTypeItemProvider.dispose();
		if (auxiliaryTrafficAreaTypeItemProvider != null) auxiliaryTrafficAreaTypeItemProvider.dispose();
		if (documentRootItemProvider != null) documentRootItemProvider.dispose();
		if (railwayTypeItemProvider != null) railwayTypeItemProvider.dispose();
		if (roadTypeItemProvider != null) roadTypeItemProvider.dispose();
		if (squareTypeItemProvider != null) squareTypeItemProvider.dispose();
		if (trackTypeItemProvider != null) trackTypeItemProvider.dispose();
		if (trafficAreaPropertyTypeItemProvider != null) trafficAreaPropertyTypeItemProvider.dispose();
		if (trafficAreaTypeItemProvider != null) trafficAreaTypeItemProvider.dispose();
		if (transportationComplexTypeItemProvider != null) transportationComplexTypeItemProvider.dispose();
	}

}
